<?php

/**
 * @file
 * Records a history of the site's user logins.
 */

use Drupal\Core\Session\AccountInterface;
use Drupal\user\UserInterface;

/**
 * Implements hook_user_login().
 * The user just logged in.
 *
 * @param $account
 *   The user object on which the operation was just performed.
 */
function login_history_user_login($account) {
  $request = \Drupal::request();
  // Is this a one-time login?
  /*$route = \Drupal::service('router')->matchRequest($request); //登录后没有权限在router了所以这句我报错。
  if ($route['_route'] == 'user.reset' && $route['operation'] == 'login') { //暂不清楚这样判断的作用。
    $one_time = 1;
  }
  else {
    $one_time = 0;
  }*/
  $one_time = 0;
  // Limit user agent strings to 255 characters. For example, some versions of
  // IE8 return long user agent strings causing an error upon login.
  $user_agent = $request->server->get('HTTP_USER_AGENT');
  if (strlen($user_agent) > 255) {
    $user_agent = substr($user_agent, 0, 255);
  }

  $login_detail = array(
    'uid' => $account->id(),
    'login' => $account->getLastLoginTime(),
    'hostname' => $request->getClientIP(),
    'one_time' => $one_time,
    'user_agent' => $user_agent,
  );

  // Now save the user's current login timestamp to login_history.
  db_insert('login_history')
    ->fields($login_detail)
    ->execute();
}



/**
 * Provide data about the last login for a user.
 *
 * @param \Drupal\Core\Session\AccountInterface $account
 *   An optional user to get the last login for.
 *
 * @return object|false
 *   An object containing information about the last login or FALSE if no
 *   result is found.
 */
function login_history_last_login(AccountInterface $account = NULL) {
  if (!$account) {
    $account = \Drupal::currentUser();
  }
  if ($account->isAnonymous()) {
    return;
  }
  $last_login = db_query("SELECT login, hostname, one_time, user_agent
                   FROM {login_history}
                   WHERE uid = :uid
                   ORDER BY login DESC
                   LIMIT 1, 2", array(':uid' => $account->id()))->fetchAll();
  return reset($last_login);
}
